name: Tag
on:
 push:
   tags:
     - v*
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Prepare gox
      run: go get github.com/mitchellh/gox
      
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Build
      run: |
        export PATH=$PATH:$HOME/go/bin
        gox
        
    - name: GH Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: |
          auto-selfreport_darwin_amd64
          auto-selfreport_freebsd_386
          auto-selfreport_freebsd_amd64
          auto-selfreport_freebsd_arm
          auto-selfreport_linux_386
          auto-selfreport_linux_amd64
          auto-selfreport_linux_arm
          auto-selfreport_linux_mips
          auto-selfreport_linux_mips64
          auto-selfreport_linux_mips64le
          auto-selfreport_linux_mipsle
          auto-selfreport_linux_s390x
          auto-selfreport_netbsd_386
          auto-selfreport_netbsd_amd64
          auto-selfreport_netbsd_arm
          auto-selfreport_openbsd_386
          auto-selfreport_openbsd_amd64
          auto-selfreport_windows_386.exe
          auto-selfreport_windows_amd64.exe
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          

